# Create image from git
# java , jre -> : gradle , eclipse-temurin ,amazoncorretto , ibm-semeru-runtimes !!!
# syntax=docker/dockerfile:1
FROM gradle:jdk21 AS build

ARG ORG_GRADLE_PROJECT_isProduction="yes"
ENV ORG_GRADLE_PROJECT_isProduction=$ORG_GRADLE_PROJECT_isProduction

WORKDIR /app

COPY --chown=gradle:gradle --from=project . /app

RUN gradle installDist

FROM eclipse-temurin:21.0.1_12-jdk-alpine as my-jdk

# required for strip-debug to work
RUN apk add --no-cache binutils

# Build small JRE image
RUN $JAVA_HOME/bin/jlink \
    --verbose \
    --add-modules java.base,jdk.crypto.ec,java.management,java.naming,java.net.http,java.security.jgss,java.security.sasl,java.sql,jdk.httpserver,jdk.unsupported \
    --strip-debug \
    --no-man-pages \
    --no-header-files \
    --compress=2 \
    --output /customjre

FROM alpine:latest
ENV JAVA_HOME=/jre
ENV PATH="${JAVA_HOME}/bin:${PATH}"

COPY --from=my-jdk /customjre $JAVA_HOME

COPY --from=build --chmod=777 /app/build/install/query-gra /app/

WORKDIR /app/bin

EXPOSE 9090

CMD ["./query-gra"]

# sudo docker buildx build -f ./Dockerfile-git --build-arg ORG_GRADLE_PROJECT_isProduction=yes  --build-context project=https://borisgra@github.com/borisgra/fullWeb.git --progress=plain -t borisgra/query-gra:latest . 2>&1 | tee build.log
# sudo docker buildx build -f ./Dockerfile-git --build-arg ORG_GRADLE_PROJECT_isProduction=yes  --build-context project=https://borisgra:gihub_token@github.com/borisgra/jvm-js-fullstack.git --progress=plain -t borisgra/query-gra:latest . 2>&1 | tee build.log
# sudo docker login -u borisgra
# sudo docker push borisgra/query-gra:latest
# sudo docker pull borisgra/query-gra:latest
# sudo docker run borisgra/query-gra:latest -p 5004:5004
#docker builder prune  # clear cache
#--no-cache

