apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: "2023-07-08T08:05:08Z"
  generateName: query-gra-7458f4d8f8-
  labels:
    app: query-gra
    pod-template-hash: 7458f4d8f8
  managedFields:
  - apiVersion: v1
    fieldsType: FieldsV1
    fieldsV1:
      f:metadata:
        f:generateName: {}
        f:labels:
          .: {}
          f:app: {}
          f:pod-template-hash: {}
        f:ownerReferences:
          .: {}
          k:{"uid":"4db564f0-3577-4a20-a9c2-3e6d441251f9"}: {}
      f:spec:
        f:containers:
          k:{"name":"query-gra-1"}:
            .: {}
            f:env:
              .: {}
              k:{"name":"DATABASE_URL_animal"}:
                .: {}
                f:name: {}
                f:valueFrom:
                  .: {}
                  f:configMapKeyRef: {}
              k:{"name":"DATABASE_URL_croach_fo"}:
                .: {}
                f:name: {}
                f:valueFrom:
                  .: {}
                  f:configMapKeyRef: {}
              k:{"name":"DATABASE_URL_daas_fo"}:
                .: {}
                f:name: {}
                f:valueFrom:
                  .: {}
                  f:configMapKeyRef: {}
              k:{"name":"DATABASE_URL_daas_nma"}:
                .: {}
                f:name: {}
                f:valueFrom:
                  .: {}
                  f:configMapKeyRef: {}
              k:{"name":"DATABASE_URL_elephant_joqivmzw"}:
                .: {}
                f:name: {}
                f:valueFrom:
                  .: {}
                  f:configMapKeyRef: {}
              k:{"name":"QUERY_BD"}:
                .: {}
                f:name: {}
                f:valueFrom:
                  .: {}
                  f:configMapKeyRef: {}
              k:{"name":"SERVER_TYPE"}:
                .: {}
                f:name: {}
                f:valueFrom:
                  .: {}
                  f:configMapKeyRef: {}
              k:{"name":"jsr223"}:
                .: {}
                f:name: {}
                f:valueFrom:
                  .: {}
                  f:configMapKeyRef: {}
              k:{"name":"q"}:
                .: {}
                f:name: {}
                f:valueFrom:
                  .: {}
                  f:configMapKeyRef: {}
            f:image: {}
            f:imagePullPolicy: {}
            f:name: {}
            f:resources: {}
            f:terminationMessagePath: {}
            f:terminationMessagePolicy: {}
        f:dnsPolicy: {}
        f:enableServiceLinks: {}
        f:restartPolicy: {}
        f:schedulerName: {}
        f:securityContext: {}
        f:terminationGracePeriodSeconds: {}
    manager: kube-controller-manager
    operation: Update
    time: "2023-07-08T08:05:08Z"
  - apiVersion: v1
    fieldsType: FieldsV1
    fieldsV1:
      f:status:
        f:conditions:
          k:{"type":"ContainersReady"}:
            .: {}
            f:lastProbeTime: {}
            f:lastTransitionTime: {}
            f:status: {}
            f:type: {}
          k:{"type":"Initialized"}:
            .: {}
            f:lastProbeTime: {}
            f:lastTransitionTime: {}
            f:status: {}
            f:type: {}
          k:{"type":"Ready"}:
            .: {}
            f:lastProbeTime: {}
            f:lastTransitionTime: {}
            f:status: {}
            f:type: {}
        f:containerStatuses: {}
        f:hostIP: {}
        f:phase: {}
        f:podIP: {}
        f:podIPs:
          .: {}
          k:{"ip":"10.56.2.4"}:
            .: {}
            f:ip: {}
        f:startTime: {}
    manager: kubelet
    operation: Update
    subresource: status
    time: "2023-07-08T08:05:19Z"
  name: query-gra-7458f4d8f8-sl6p5
  namespace: default
  ownerReferences:
  - apiVersion: apps/v1
    blockOwnerDeletion: true
    controller: true
    kind: ReplicaSet
    name: query-gra-7458f4d8f8
    uid: 4db564f0-3577-4a20-a9c2-3e6d441251f9
  resourceVersion: "1390"
  uid: 108ee05d-c5f0-4b01-9c8b-4df0885c7edf
spec:
  containers:
  - env:
    - name: SERVER_TYPE
      valueFrom:
        configMapKeyRef:
          key: SERVER_TYPE
          name: query-gra-config-z3k8
    - name: jsr223
      valueFrom:
        configMapKeyRef:
          key: jsr223
          name: query-gra-config-z3k8
    - name: DATABASE_URL_elephant_joqivmzw
      valueFrom:
        configMapKeyRef:
          key: DATABASE_URL_elephant_joqivmzw
          name: query-gra-config-z3k8
    - name: DATABASE_URL_croach_fo
      valueFrom:
        configMapKeyRef:
          key: DATABASE_URL_croach_fo
          name: query-gra-config-z3k8
    - name: DATABASE_URL_daas_nma
      valueFrom:
        configMapKeyRef:
          key: DATABASE_URL_daas_nma
          name: query-gra-config-z3k8
    - name: QUERY_BD
      valueFrom:
        configMapKeyRef:
          key: QUERY_BD
          name: query-gra-config-z3k8
    - name: q
      valueFrom:
        configMapKeyRef:
          key: q
          name: query-gra-config-z3k8
    - name: DATABASE_URL_animal
      valueFrom:
        configMapKeyRef:
          key: DATABASE_URL_animal
          name: query-gra-config-z3k8
    - name: DATABASE_URL_daas_fo
      valueFrom:
        configMapKeyRef:
          key: DATABASE_URL_daas_fo
          name: query-gra-config-z3k8
    image: borisgra/query-gra:jsr223
    imagePullPolicy: IfNotPresent
    name: query-gra-1
    resources: {}
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: File
    volumeMounts:
    - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      name: kube-api-access-tqnhv
      readOnly: true
  dnsPolicy: ClusterFirst
  enableServiceLinks: true
  nodeName: gke-query-gra-cluster-default-pool-f6f702aa-dnqx
  preemptionPolicy: PreemptLowerPriority
  priority: 0
  restartPolicy: Always
  schedulerName: default-scheduler
  securityContext: {}
  serviceAccount: default
  serviceAccountName: default
  terminationGracePeriodSeconds: 30
  tolerations:
  - effect: NoExecute
    key: node.kubernetes.io/not-ready
    operator: Exists
    tolerationSeconds: 300
  - effect: NoExecute
    key: node.kubernetes.io/unreachable
    operator: Exists
    tolerationSeconds: 300
  volumes:
  - name: kube-api-access-tqnhv
    projected:
      defaultMode: 420
      sources:
      - serviceAccountToken:
          expirationSeconds: 3607
          path: token
      - configMap:
          items:
          - key: ca.crt
            path: ca.crt
          name: kube-root-ca.crt
      - downwardAPI:
          items:
          - fieldRef:
              apiVersion: v1
              fieldPath: metadata.namespace
            path: namespace
status:
  conditions:
  - lastProbeTime: null
    lastTransitionTime: "2023-07-08T08:05:08Z"
    status: "True"
    type: Initialized
  - lastProbeTime: null
    lastTransitionTime: "2023-07-08T08:05:19Z"
    status: "True"
    type: Ready
  - lastProbeTime: null
    lastTransitionTime: "2023-07-08T08:05:19Z"
    status: "True"
    type: ContainersReady
  - lastProbeTime: null
    lastTransitionTime: "2023-07-08T08:05:08Z"
    status: "True"
    type: PodScheduled
  containerStatuses:
  - containerID: containerd://39ea27b1edef1581b0a2cd063ad8cd3f504d1ce8ad3a7d09923f4aed23ae50cb
    image: docker.io/borisgra/query-gra:jsr223
    imageID: docker.io/borisgra/query-gra@sha256:bf97316bba8893f0c7cc46d69f6b2141d2333c9e03a01902cfe474855901db5d
    lastState: {}
    name: query-gra-1
    ready: true
    restartCount: 0
    started: true
    state:
      running:
        startedAt: "2023-07-08T08:05:19Z"
  hostIP: 10.128.0.17
  phase: Running
  podIP: 10.56.2.4
  podIPs:
  - ip: 10.56.2.4
  qosClass: BestEffort
  startTime: "2023-07-08T08:05:08Z"
